
# 多数据源配置
spring:
  datasource:
    initialization-mode: always
    druid:
      security:
        enable: false
        username: root
        password: root
    dynamic:
      master:
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:9099/upms-db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        druid:
          initial-size: 5
          max-active: 10
          min-idle: 5
          max-wait: 60000
          min-evictable-idle-time-millis: 30000
          max-evictable-idle-time-millis: 30000
          time-between-eviction-runs-millis: 0
          validation-query: SELECT 1
          validation-query-timeout: -1
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          pool-prepared-statements: true
          max-open-prepared-statements: 100
          filters: stat,wall
          share-prepared-statements: true

 # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 30000
    testOnBorrow: false
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
      max-total: 100000

